spring:
  rabbitmq:
    host: 192.168.199.12
    username: rabbitmq
    password: rabbitmq
    #开启发送失败返回
    publisher-returns: true
    #开启发送确认
#    publisher-confirm-type: CORRELATED
    listener:
      direct:
        acknowledge-mode: auto
        prefetch: 1
